spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#  security:
#    user:
#      name: admin
#      password: 123456

jwt:
  # 签发人
  issuer: mirror
  # 秘钥
  secret: FwEQmdctWwf0Gx7Tb0nUtQ7ZA9fB5io5+gLH6qedlyUvA24IzsI7YoSzzcMZxEX/+AaNpxdjII+HIfKZAN2H2A==
    # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
    # token 请求头中的 key 值
  tokenHeaderKey: Authorization
    # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

#=================================================================
# minio
#=================================================================
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: mirror
  secretKey: makai2001
  bucketName: weblog

